/*
 * Deel REST API
 * Deel REST API
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateContract201ResponseDataCompensationDetails
 */
public class CreateContract201ResponseDataCompensationDetailsTest {
    private final CreateContract201ResponseDataCompensationDetails model = new CreateContract201ResponseDataCompensationDetails();

    /**
     * Model tests for CreateContract201ResponseDataCompensationDetails
     */
    @Test
    public void testCreateContract201ResponseDataCompensationDetails() {
        // TODO: test CreateContract201ResponseDataCompensationDetails
    }

    /**
     * Test the property 'scale'
     */
    @Test
    public void scaleTest() {
        // TODO: test scale
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'frequency'
     */
    @Test
    public void frequencyTest() {
        // TODO: test frequency
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'firstPayment'
     */
    @Test
    public void firstPaymentTest() {
        // TODO: test firstPayment
    }

    /**
     * Test the property 'firstPaymentDate'
     */
    @Test
    public void firstPaymentDateTest() {
        // TODO: test firstPaymentDate
    }

    /**
     * Test the property 'grossAnnualSalary'
     */
    @Test
    public void grossAnnualSalaryTest() {
        // TODO: test grossAnnualSalary
    }

    /**
     * Test the property 'grossSigningBonus'
     */
    @Test
    public void grossSigningBonusTest() {
        // TODO: test grossSigningBonus
    }

    /**
     * Test the property 'grossVariableBonus'
     */
    @Test
    public void grossVariableBonusTest() {
        // TODO: test grossVariableBonus
    }

}
