/*
 * Deel REST API
 * Deel REST API
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateEorContractRequestEmployment
 */
public class CreateEorContractRequestEmploymentTest {
    private final CreateEorContractRequestEmployment model = new CreateEorContractRequestEmployment();

    /**
     * Model tests for CreateEorContractRequestEmployment
     */
    @Test
    public void testCreateEorContractRequestEmployment() {
        // TODO: test CreateEorContractRequestEmployment
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'scopeOfWork'
     */
    @Test
    public void scopeOfWorkTest() {
        // TODO: test scopeOfWork
    }

    /**
     * Test the property 'workVisaRequired'
     */
    @Test
    public void workVisaRequiredTest() {
        // TODO: test workVisaRequired
    }

}
