/*
 * Deel REST API
 * Deel REST API
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateLegalEntityRequestDataCompanyIdentifiers
 */
public class CreateLegalEntityRequestDataCompanyIdentifiersTest {
    private final CreateLegalEntityRequestDataCompanyIdentifiers model = new CreateLegalEntityRequestDataCompanyIdentifiers();

    /**
     * Model tests for CreateLegalEntityRequestDataCompanyIdentifiers
     */
    @Test
    public void testCreateLegalEntityRequestDataCompanyIdentifiers() {
        // TODO: test CreateLegalEntityRequestDataCompanyIdentifiers
    }

    /**
     * Test the property 'taxNumber'
     */
    @Test
    public void taxNumberTest() {
        // TODO: test taxNumber
    }

    /**
     * Test the property 'registrationNumber'
     */
    @Test
    public void registrationNumberTest() {
        // TODO: test registrationNumber
    }

}
