/*
 * Deel REST API
 * Deel REST API
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Attachment;
import org.openapitools.client.model.TimeOffDate;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateTimeOffRequestBodyData
 */
public class CreateTimeOffRequestBodyDataTest {
    private final CreateTimeOffRequestBodyData model = new CreateTimeOffRequestBodyData();

    /**
     * Model tests for CreateTimeOffRequestBodyData
     */
    @Test
    public void testCreateTimeOffRequestBodyData() {
        // TODO: test CreateTimeOffRequestBodyData
    }

    /**
     * Test the property 'recipientProfileId'
     */
    @Test
    public void recipientProfileIdTest() {
        // TODO: test recipientProfileId
    }

    /**
     * Test the property 'otherTypeDescription'
     */
    @Test
    public void otherTypeDescriptionTest() {
        // TODO: test otherTypeDescription
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'timeOffTypeId'
     */
    @Test
    public void timeOffTypeIdTest() {
        // TODO: test timeOffTypeId
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'deductionAmount'
     */
    @Test
    public void deductionAmountTest() {
        // TODO: test deductionAmount
    }

    /**
     * Test the property 'isPaid'
     */
    @Test
    public void isPaidTest() {
        // TODO: test isPaid
    }

    /**
     * Test the property 'contractOid'
     */
    @Test
    public void contractOidTest() {
        // TODO: test contractOid
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

    /**
     * Test the property 'dates'
     */
    @Test
    public void datesTest() {
        // TODO: test dates
    }

    /**
     * Test the property 'timeOffPercentage'
     */
    @Test
    public void timeOffPercentageTest() {
        // TODO: test timeOffPercentage
    }

}
