/*
 * Deel REST API
 * Deel REST API
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.GetBenefitEmployee200ResponseContractsInnerCompensationsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetBenefitEmployee200ResponseContractsInner
 */
public class GetBenefitEmployee200ResponseContractsInnerTest {
    private final GetBenefitEmployee200ResponseContractsInner model = new GetBenefitEmployee200ResponseContractsInner();

    /**
     * Model tests for GetBenefitEmployee200ResponseContractsInner
     */
    @Test
    public void testGetBenefitEmployee200ResponseContractsInner() {
        // TODO: test GetBenefitEmployee200ResponseContractsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'flsa'
     */
    @Test
    public void flsaTest() {
        // TODO: test flsa
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'jobTitle'
     */
    @Test
    public void jobTitleTest() {
        // TODO: test jobTitle
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'compensations'
     */
    @Test
    public void compensationsTest() {
        // TODO: test compensations
    }

    /**
     * Test the property 'contractType'
     */
    @Test
    public void contractTypeTest() {
        // TODO: test contractType
    }

    /**
     * Test the property 'employmentType'
     */
    @Test
    public void employmentTypeTest() {
        // TODO: test employmentType
    }

    /**
     * Test the property 'estimatedWeekWorkingHours'
     */
    @Test
    public void estimatedWeekWorkingHoursTest() {
        // TODO: test estimatedWeekWorkingHours
    }

}
