/*
 * Deel REST API
 * Deel REST API
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetEORContractBenefits200ResponseDataInnerEnrollmentDetailsPlan
 */
public class GetEORContractBenefits200ResponseDataInnerEnrollmentDetailsPlanTest {
    private final GetEORContractBenefits200ResponseDataInnerEnrollmentDetailsPlan model = new GetEORContractBenefits200ResponseDataInnerEnrollmentDetailsPlan();

    /**
     * Model tests for GetEORContractBenefits200ResponseDataInnerEnrollmentDetailsPlan
     */
    @Test
    public void testGetEORContractBenefits200ResponseDataInnerEnrollmentDetailsPlan() {
        // TODO: test GetEORContractBenefits200ResponseDataInnerEnrollmentDetailsPlan
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
