/*
 * Deel REST API
 * Deel REST API
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetGrossToNetGPReports200ResponseDataInner
 */
public class GetGrossToNetGPReports200ResponseDataInnerTest {
    private final GetGrossToNetGPReports200ResponseDataInner model = new GetGrossToNetGPReports200ResponseDataInner();

    /**
     * Model tests for GetGrossToNetGPReports200ResponseDataInner
     */
    @Test
    public void testGetGrossToNetGPReports200ResponseDataInner() {
        // TODO: test GetGrossToNetGPReports200ResponseDataInner
    }

    /**
     * Test the property 'netPay'
     */
    @Test
    public void netPayTest() {
        // TODO: test netPay
    }

    /**
     * Test the property 'eeLoans'
     */
    @Test
    public void eeLoansTest() {
        // TODO: test eeLoans
    }

    /**
     * Test the property 'contractId'
     */
    @Test
    public void contractIdTest() {
        // TODO: test contractId
    }

    /**
     * Test the property 'costCenter'
     */
    @Test
    public void costCenterTest() {
        // TODO: test costCenter
    }

    /**
     * Test the property 'annualBonus'
     */
    @Test
    public void annualBonusTest() {
        // TODO: test annualBonus
    }

    /**
     * Test the property 'carAllowance'
     */
    @Test
    public void carAllowanceTest() {
        // TODO: test carAllowance
    }

    /**
     * Test the property 'eeIncomeTax'
     */
    @Test
    public void eeIncomeTaxTest() {
        // TODO: test eeIncomeTax
    }

    /**
     * Test the property 'employeeName'
     */
    @Test
    public void employeeNameTest() {
        // TODO: test employeeName
    }

    /**
     * Test the property 'employerCost'
     */
    @Test
    public void employerCostTest() {
        // TODO: test employerCost
    }

    /**
     * Test the property 'espDeduction'
     */
    @Test
    public void espDeductionTest() {
        // TODO: test espDeduction
    }

    /**
     * Test the property 'fundingAmount'
     */
    @Test
    public void fundingAmountTest() {
        // TODO: test fundingAmount
    }

    /**
     * Test the property 'homeAllowance'
     */
    @Test
    public void homeAllowanceTest() {
        // TODO: test homeAllowance
    }

    /**
     * Test the property 'employeeNumber'
     */
    @Test
    public void employeeNumberTest() {
        // TODO: test employeeNumber
    }

    /**
     * Test the property 'backdatedSalary'
     */
    @Test
    public void backdatedSalaryTest() {
        // TODO: test backdatedSalary
    }

    /**
     * Test the property 'employeeDivision'
     */
    @Test
    public void employeeDivisionTest() {
        // TODO: test employeeDivision
    }

    /**
     * Test the property 'employeeJobTitle'
     */
    @Test
    public void employeeJobTitleTest() {
        // TODO: test employeeJobTitle
    }

    /**
     * Test the property 'employeeDepartment'
     */
    @Test
    public void employeeDepartmentTest() {
        // TODO: test employeeDepartment
    }

    /**
     * Test the property 'erOccupationalRisk'
     */
    @Test
    public void erOccupationalRiskTest() {
        // TODO: test erOccupationalRisk
    }

    /**
     * Test the property 'pensionContribution'
     */
    @Test
    public void pensionContributionTest() {
        // TODO: test pensionContribution
    }

    /**
     * Test the property 'employerContribution'
     */
    @Test
    public void employerContributionTest() {
        // TODO: test employerContribution
    }

    /**
     * Test the property 'employmentStatusTagInternal'
     */
    @Test
    public void employmentStatusTagInternalTest() {
        // TODO: test employmentStatusTagInternal
    }

}
