/*
 * Deel REST API
 * Deel REST API
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetPeoplePersonalInformationById200ResponseDataKyc
 */
public class GetPeoplePersonalInformationById200ResponseDataKycTest {
    private final GetPeoplePersonalInformationById200ResponseDataKyc model = new GetPeoplePersonalInformationById200ResponseDataKyc();

    /**
     * Model tests for GetPeoplePersonalInformationById200ResponseDataKyc
     */
    @Test
    public void testGetPeoplePersonalInformationById200ResponseDataKyc() {
        // TODO: test GetPeoplePersonalInformationById200ResponseDataKyc
    }

    /**
     * Test the property 'isKycApproved'
     */
    @Test
    public void isKycApprovedTest() {
        // TODO: test isKycApproved
    }

    /**
     * Test the property 'kycApprovalDate'
     */
    @Test
    public void kycApprovalDateTest() {
        // TODO: test kycApprovalDate
    }

}
