/*
 * Deel REST API
 * Deel REST API
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetPeoplePersonalInformationById200ResponseDataDemographicsGender
 */
public class GetPeoplePersonalInformationById200ResponseDataDemographicsGenderTest {
    private final GetPeoplePersonalInformationById200ResponseDataDemographicsGender model = new GetPeoplePersonalInformationById200ResponseDataDemographicsGender();

    /**
     * Model tests for GetPeoplePersonalInformationById200ResponseDataDemographicsGender
     */
    @Test
    public void testGetPeoplePersonalInformationById200ResponseDataDemographicsGender() {
        // TODO: test GetPeoplePersonalInformationById200ResponseDataDemographicsGender
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'otherName'
     */
    @Test
    public void otherNameTest() {
        // TODO: test otherName
    }

}
