/*
 * Deel REST API
 * Deel REST API
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for HrisJobInformationTitleId
 */
public class HrisJobInformationTitleIdTest {
    private final HrisJobInformationTitleId model = new HrisJobInformationTitleId();

    /**
     * Model tests for HrisJobInformationTitleId
     */
    @Test
    public void testHrisJobInformationTitleId() {
        // TODO: test HrisJobInformationTitleId
    }

    /**
     * Test the property 'seniorityId'
     */
    @Test
    public void seniorityIdTest() {
        // TODO: test seniorityId
    }

    /**
     * Test the property 'jobTitleId'
     */
    @Test
    public void jobTitleIdTest() {
        // TODO: test jobTitleId
    }

}
