/*
 * Deel REST API
 * Deel REST API
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Contribution;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PensionProvider
 */
public class PensionProviderTest {
    private final PensionProvider model = new PensionProvider();

    /**
     * Model tests for PensionProvider
     */
    @Test
    public void testPensionProvider() {
        // TODO: test PensionProvider
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'homePageUrl'
     */
    @Test
    public void homePageUrlTest() {
        // TODO: test homePageUrl
    }

    /**
     * Test the property 'contribution'
     */
    @Test
    public void contributionTest() {
        // TODO: test contribution
    }

}
