/*
 * Deel REST API
 * Deel REST API
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import org.openapitools.client.model.InvoiceAdjustmentSearchContainerContractTypes;
import org.openapitools.client.model.SortDirEnum;
import org.openapitools.client.model.TimesheetSearchContainerStatuses;
import org.openapitools.client.model.TimesheetSearchContainerTypes;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TimesheetSearchContainer
 */
public class TimesheetSearchContainerTest {
    private final TimesheetSearchContainer model = new TimesheetSearchContainer();

    /**
     * Model tests for TimesheetSearchContainer
     */
    @Test
    public void testTimesheetSearchContainer() {
        // TODO: test TimesheetSearchContainer
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'orderDirection'
     */
    @Test
    public void orderDirectionTest() {
        // TODO: test orderDirection
    }

    /**
     * Test the property 'contractId'
     */
    @Test
    public void contractIdTest() {
        // TODO: test contractId
    }

    /**
     * Test the property 'invoiceId'
     */
    @Test
    public void invoiceIdTest() {
        // TODO: test invoiceId
    }

    /**
     * Test the property 'reporterId'
     */
    @Test
    public void reporterIdTest() {
        // TODO: test reporterId
    }

    /**
     * Test the property 'contractTypes'
     */
    @Test
    public void contractTypesTest() {
        // TODO: test contractTypes
    }

    /**
     * Test the property 'types'
     */
    @Test
    public void typesTest() {
        // TODO: test types
    }

    /**
     * Test the property 'statuses'
     */
    @Test
    public void statusesTest() {
        // TODO: test statuses
    }

    /**
     * Test the property 'dateFrom'
     */
    @Test
    public void dateFromTest() {
        // TODO: test dateFrom
    }

    /**
     * Test the property 'dateTo'
     */
    @Test
    public void dateToTest() {
        // TODO: test dateTo
    }

}
