/*
 * Deel REST API
 * Deel REST API
 *
 * The version of the OpenAPI document: 1.25.0
 * Contact: apiteam@deel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PeoplePersonalContainerDataPhoneNumbersInner;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserPersonalInformationToUpdateContainerData
 */
public class UserPersonalInformationToUpdateContainerDataTest {
    private final UserPersonalInformationToUpdateContainerData model = new UserPersonalInformationToUpdateContainerData();

    /**
     * Model tests for UserPersonalInformationToUpdateContainerData
     */
    @Test
    public void testUserPersonalInformationToUpdateContainerData() {
        // TODO: test UserPersonalInformationToUpdateContainerData
    }

    /**
     * Test the property 'legalFirstName'
     */
    @Test
    public void legalFirstNameTest() {
        // TODO: test legalFirstName
    }

    /**
     * Test the property 'legalLastName'
     */
    @Test
    public void legalLastNameTest() {
        // TODO: test legalLastName
    }

    /**
     * Test the property 'preferredName'
     */
    @Test
    public void preferredNameTest() {
        // TODO: test preferredName
    }

    /**
     * Test the property 'personalEmail'
     */
    @Test
    public void personalEmailTest() {
        // TODO: test personalEmail
    }

    /**
     * Test the property 'workEmail'
     */
    @Test
    public void workEmailTest() {
        // TODO: test workEmail
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'phoneNumbers'
     */
    @Test
    public void phoneNumbersTest() {
        // TODO: test phoneNumbers
    }

}
